//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifesAssistant.Properties.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifesAssistant.Properties.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add HB.
        /// </summary>
        public static string addHBFloLabelyout {
            get {
                return ResourceManager.GetString("addHBFloLabelyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new HB.
        /// </summary>
        public static string addHBLabel {
            get {
                return ResourceManager.GetString("addHBLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addLabel {
            get {
                return ResourceManager.GetString("addLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new money operation.
        /// </summary>
        public static string addNewMoneyOperLabel {
            get {
                return ResourceManager.GetString("addNewMoneyOperLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new sleeps time.
        /// </summary>
        public static string addNewSleepTimeLabel {
            get {
                return ResourceManager.GetString("addNewSleepTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new water operation.
        /// </summary>
        public static string addNewWaterOperLabel {
            get {
                return ResourceManager.GetString("addNewWaterOperLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add task.
        /// </summary>
        public static string addTaskLabel {
            get {
                return ResourceManager.GetString("addTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string calendarTabLabel {
            get {
                return ResourceManager.GetString("calendarTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string capacityHeader {
            get {
                return ResourceManager.GetString("capacityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity: .
        /// </summary>
        public static string capacityLabel {
            get {
                return ResourceManager.GetString("capacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart elements group by: .
        /// </summary>
        public static string chartsByLabel {
            get {
                return ResourceManager.GetString("chartsByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily costs.
        /// </summary>
        public static string creditTabName {
            get {
                return ResourceManager.GetString("creditTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string dateLabel {
            get {
                return ResourceManager.GetString("dateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string dayLabel {
            get {
                return ResourceManager.GetString("dayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deleteLabel {
            get {
                return ResourceManager.GetString("deleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dell.
        /// </summary>
        public static string dellLabel {
            get {
                return ResourceManager.GetString("dellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        public static string descriptionsHeader {
            get {
                return ResourceManager.GetString("descriptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions:.
        /// </summary>
        public static string descriptionsLabel {
            get {
                return ResourceManager.GetString("descriptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping time.
        /// </summary>
        public static string dreamTabName {
            get {
                return ResourceManager.GetString("dreamTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durations.
        /// </summary>
        public static string durationHeader {
            get {
                return ResourceManager.GetString("durationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string findLabel {
            get {
                return ResourceManager.GetString("findLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string finishHeader {
            get {
                return ResourceManager.GetString("finishHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish dream:.
        /// </summary>
        public static string finishSleepingLabel {
            get {
                return ResourceManager.GetString("finishSleepingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HB List: .
        /// </summary>
        public static string hbListLabel {
            get {
                return ResourceManager.GetString("hbListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Charts  ▲.
        /// </summary>
        public static string hideChartsLabel {
            get {
                return ResourceManager.GetString("hideChartsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Tasks ▲.
        /// </summary>
        public static string hideTasksLabel {
            get {
                return ResourceManager.GetString("hideTasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from the latest sleep.
        /// </summary>
        public static string lastSleepingLabel {
            get {
                return ResourceManager.GetString("lastSleepingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time from the latest water drink.
        /// </summary>
        public static string lastWaterDrinkingLabel {
            get {
                return ResourceManager.GetString("lastWaterDrinkingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string moneyHeader {
            get {
                return ResourceManager.GetString("moneyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money:.
        /// </summary>
        public static string moneyLabel {
            get {
                return ResourceManager.GetString("moneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string monthLabel {
            get {
                return ResourceManager.GetString("monthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nameHeader {
            get {
                return ResourceManager.GetString("nameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string nameLabel {
            get {
                return ResourceManager.GetString("nameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new task.
        /// </summary>
        public static string newTaskLabel {
            get {
                return ResourceManager.GetString("newTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string purchaseHeader {
            get {
                return ResourceManager.GetString("purchaseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase:.
        /// </summary>
        public static string purchaseLabel {
            get {
                return ResourceManager.GetString("purchaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts  ▼.
        /// </summary>
        public static string showChartsLabel {
            get {
                return ResourceManager.GetString("showChartsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Task ▼.
        /// </summary>
        public static string showTasksLabel {
            get {
                return ResourceManager.GetString("showTasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of sleep:.
        /// </summary>
        public static string sleepDurationLabel {
            get {
                return ResourceManager.GetString("sleepDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string startHeader {
            get {
                return ResourceManager.GetString("startHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin dream:.
        /// </summary>
        public static string startSleepingLabel {
            get {
                return ResourceManager.GetString("startSleepingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task list.
        /// </summary>
        public static string taskListLabel {
            get {
                return ResourceManager.GetString("taskListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string timeHeader {
            get {
                return ResourceManager.GetString("timeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string timeLabel {
            get {
                return ResourceManager.GetString("timeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today: .
        /// </summary>
        public static string todayLabel {
            get {
                return ResourceManager.GetString("todayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total costs today: .
        /// </summary>
        public static string totalCostsLable {
            get {
                return ResourceManager.GetString("totalCostsLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sleep time:.
        /// </summary>
        public static string totalSleepLabel {
            get {
                return ResourceManager.GetString("totalSleepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View tasks.
        /// </summary>
        public static string viewTaskLabel {
            get {
                return ResourceManager.GetString("viewTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily water balance.
        /// </summary>
        public static string waterTabName {
            get {
                return ResourceManager.GetString("waterTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string yearLabel {
            get {
                return ResourceManager.GetString("yearLabel", resourceCulture);
            }
        }
    }
}
